[package]
name = "keytool"
authors = ['Clover Network <https://github.com/clover-network>']
edition = '2021'
license = 'GPL-3.0'
homepage = 'https://clover.finance'
repository = 'https://github.com/clover-network/clover'
version = '0.9.0'

[[bin]]
name = "keytool"
path = "src/main.rs"

[dependencies]
structopt = { workspace = true }
secp256k1 = { workspace = true }
tiny-bip39 = { workspace = true }
tiny-hderive = { workspace = true }
sha3 = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
